#!/usr/bin/env node
import { promises as fs } from "node:fs";
import { execFile } from "node:child_process";
import { join } from "node:path";

const root = process.env.WORK_PROJECTS_ROOT || "/home/agent/work/projects";
const baseDomain = (process.env.PI_PROJECTS_PUBLIC_BASE_URL || "apps.it101.org").replace(/^https?:\/\//, "").replace(/\/$/, "");
const outPath = process.env.PI_CADDY_DYNAMIC_CONFIG_PATH || "/etc/caddy/Caddyfile.projects";
const caddyValidateCmd = process.env.PI_CADDY_VALIDATE_CMD || "caddy";
const caddyReloadCmd = process.env.PI_CADDY_RELOAD_CMD || "systemctl";

function run(command: string, args: string[]): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile(command, args, { timeout: 60_000 }, (error, stdout, stderr) => {
      const code = typeof (error as NodeJS.ErrnoException | null)?.code === "number" ? Number((error as NodeJS.ErrnoException).code) : error ? 1 : 0;
      resolve({ code, stdout: String(stdout || ""), stderr: String(stderr || "") });
    });
  });
}

async function hashPassword(plain: string): Promise<string> {
  const out = await run("caddy", ["hash-password", "--plaintext", plain]);
  if (out.code !== 0 || !out.stdout.trim()) {
    throw new Error(`failed to hash password: ${out.stderr || out.stdout}`);
  }
  return out.stdout.trim();
}

function envValue(text: string, key: string): string | undefined {
  const line = text.split(/\r?\n/).find((entry) => entry.startsWith(`${key}=`));
  return line ? line.slice(key.length + 1).trim().replace(/^["']|["']$/g, "") : undefined;
}

async function enabled(name: string): Promise<boolean> {
  try {
    const y = await fs.readFile(join(root, name, ".expose.yml"), "utf8");
    return /enabled:\s*true\b/i.test(y);
  } catch {
    return false;
  }
}

async function appEnv(name: string): Promise<{ port?: number; user?: string; pass?: string; publicUrl?: string }> {
  try {
    const env = await fs.readFile(join(root, name, ".env"), "utf8");
    const v = envValue(env, "APP_PORT");
    const n = Number(v);
    return {
      port: Number.isInteger(n) && n >= 1 && n <= 65535 ? n : undefined,
      user: envValue(env, "APP_BASIC_AUTH_USER") || "pidev0",
      pass: envValue(env, "APP_BASIC_AUTH_PASS"),
      publicUrl: envValue(env, "APP_PUBLIC_URL"),
    };
  } catch {
    return {};
  }
}

async function main() {
  const names = await fs.readdir(root).catch(() => [] as string[]);
  const routes: string[] = [];
  for (const name of names) {
    if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) continue;
    if (!(await enabled(name))) continue;
    const app = await appEnv(name);
    if (!app.port) {
      console.log(`skip ${name}: APP_PORT missing/invalid`);
      continue;
    }
    const host = (app.publicUrl || `https://${name}-${baseDomain}/`).replace(/^https?:\/\//, "").replace(/\/$/, "");
    const auth = app.pass ? `\n  basicauth {\n    ${app.user || "pidev0"} ${await hashPassword(app.pass)}\n  }` : "";
    routes.push(`http://${host} {${auth}\n  reverse_proxy 127.0.0.1:${app.port}\n}`);
  }

  const content = [
    "# generated by scripts/sync-ingress.ts",
    ...routes,
    "",
  ].join("\n");

  const tmp = `${outPath}.tmp`;
  const bak = `${outPath}.bak`;
  await fs.writeFile(tmp, content, "utf8");

  const validate = await run(caddyValidateCmd, ["validate", "--config", tmp]);
  if (validate.code !== 0) {
    console.error(`caddy validate failed:\n${validate.stderr || validate.stdout}`);
    process.exit(2);
  }

  try {
    await fs.copyFile(outPath, bak);
  } catch {}
  await fs.rename(tmp, outPath);

  const reload = caddyReloadCmd === "systemctl"
    ? await run("systemctl", ["reload", "caddy"])
    : await run(caddyReloadCmd, []);

  if (reload.code !== 0) {
    console.error(`caddy reload failed:\n${reload.stderr || reload.stdout}`);
    if (await fs.stat(bak).then(() => true).catch(() => false)) {
      await fs.copyFile(bak, outPath);
      await run("systemctl", ["reload", "caddy"]);
      console.error("rolled back to last-known-good");
    }
    process.exit(3);
  }

  console.log(`ok: ${routes.length} published routes`);
}

main();
