#!/usr/bin/env node
/**
 * Dynamic Caddy ingress sync for project publishing
 * Reuses the shared fail-closed expose validator before generating any route
 */

import { promises as fs } from "node:fs";
import { execFile } from "node:child_process";

import { readProjectEnv, validateProjectsExpose, type ExposeValidationResult } from "./expose-validation.ts";

const root = process.env.WORK_PROJECTS_ROOT || "/home/agent/work/projects";
const baseDomain = (process.env.PI_PROJECTS_PUBLIC_BASE_URL || "apps.it101.org").replace(/^https?:\/\//, "").replace(/\/$/, "");
const outPath = process.env.PI_CADDY_DYNAMIC_CONFIG_PATH || "/etc/caddy/Caddyfile.projects";
const caddyValidateCmd = process.env.PI_CADDY_VALIDATE_CMD || "caddy";
const caddyReloadCmd = process.env.PI_CADDY_RELOAD_CMD || "systemctl";

function run(command: string, args: string[]): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile(command, args, { timeout: 60_000 }, (error, stdout, stderr) => {
      const code = typeof (error as NodeJS.ErrnoException | null)?.code === "number" ? Number((error as NodeJS.ErrnoException).code) : error ? 1 : 0;
      resolve({ code, stdout: String(stdout || ""), stderr: String(stderr || "") });
    });
  });
}

async function hashPassword(plain: string): Promise<string> {
  const out = await run("caddy", ["hash-password", "--plaintext", plain]);
  if (out.code !== 0 || !out.stdout.trim()) {
    throw new Error(`failed to hash password: ${out.stderr || out.stdout}`);
  }
  return out.stdout.trim();
}

function logSkip(result: ExposeValidationResult): void {
  if (result.ok) return;
  console.log(JSON.stringify({ event: "ingress_skip", project: result.name, ok: false, reason: result.reason, detail: result.detail || "" }));
}

async function appAuth(name: string): Promise<{ user: string; pass?: string; publicUrl?: string }> {
  const env = await readProjectEnv(root, name);
  return {
    user: env.APP_BASIC_AUTH_USER || "pidev0",
    pass: env.APP_BASIC_AUTH_PASS,
    publicUrl: env.APP_PUBLIC_URL,
  };
}

async function main() {
  const results = await validateProjectsExpose(root);
  const routes: string[] = [];
  for (const result of results) {
    if (!result.ok) {
      logSkip(result);
      continue;
    }
    const app = await appAuth(result.name);
    const host = (app.publicUrl || `https://${result.name}-${baseDomain}/`).replace(/^https?:\/\//, "").replace(/\/$/, "");
    const auth = app.pass ? `\n  basicauth {\n    ${app.user || "pidev0"} ${await hashPassword(app.pass)}\n  }` : "";
    routes.push(`http://${host} {${auth}\n  reverse_proxy 127.0.0.1:${result.port}\n}`);
  }

  const content = [
    "# generated by scripts/sync-ingress.ts",
    ...routes,
    "",
  ].join("\n");

  const tmp = `${outPath}.tmp`;
  const bak = `${outPath}.bak`;
  await fs.writeFile(tmp, content, "utf8");

  const validate = await run(caddyValidateCmd, ["validate", "--config", tmp]);
  if (validate.code !== 0) {
    console.error(`caddy validate failed:\n${validate.stderr || validate.stdout}`);
    process.exit(2);
  }

  try {
    await fs.copyFile(outPath, bak);
  } catch {}
  await fs.rename(tmp, outPath);

  const reload = caddyReloadCmd === "systemctl"
    ? await run("systemctl", ["reload", "caddy"])
    : await run(caddyReloadCmd, []);

  if (reload.code !== 0) {
    console.error(`caddy reload failed:\n${reload.stderr || reload.stdout}`);
    if (await fs.stat(bak).then(() => true).catch(() => false)) {
      await fs.copyFile(bak, outPath);
      await run("systemctl", ["reload", "caddy"]);
      console.error("rolled back to last-known-good");
    }
    process.exit(3);
  }

  console.log(`ok: ${routes.length} published routes`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
